#valores padrões para o Helm Chart


#Aplicação
app:
  name: lncr-app
  replicas: 2  # Aumentando réplicas padrão
  image:
    repository: lanches-caieiras
    tag: latest
    pullPolicy: IfNotPresent
  port: 8080
  containerName: lncr-app
  baseUrl: http://localhost:8080
  mercadopago:
    oauthUrl: https://api.mercadopago.com/oauth/token
    ordersUrl: https://api.mercadopago.com/v1/orders
    clientId: ${MERCADOPAGO_CLIENT_ID}
    secretId: ${MERCADOPAGO_SECRET_ID}
    posId: ${MERCADOPAGO_POS_ID}

service:
  lb:
    type: LoadBalancer
    port: 8080
    targetPort: 8080
    protocol: TCP
    name: http

#Banco de dados
postgres:
  image: postgres:15.7
  containerName: lncr-db
  name: lncr-db
  url: jdbc:postgresql://lncr-db:5432/postgres
  database: postgres
  storage: "${PWD}/db"
  ports:
    service: 5432
    targetPort: 5432
    containerPort: 5432
    protocol: TCP

#Storage
storage:
  images:
    size: "10Gi"
    mountPath: "/app/images"
    hostPath: "${PWD}/images"
    # storageClass: "standard"  # Comentado para usar o storageClass padrão do cluster
    accessMode: "ReadWriteOnce"
  database:
    size: "5Gi"
    mountPath: "/var/lib/postgresql/data"
    hostPath: "${PWD}/data/postgres"
    accessMode: "ReadWriteOnce"
#Deployment
resources:
  lanchesCaieirasApp:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  postgres:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
#HPA
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 70

#Secrets
secrets:
  postgresPassword: ${POSTGRES_PASSWORD}
  postgresUser: ${POSTGRES_USER}
  mercadopagoClientId: ${MERCADOPAGO_CLIENT_ID}
  mercadopagoSecretId: ${MERCADOPAGO_SECRET_ID}
  mercadopagoPosId: ${MERCADOPAGO_POS_ID}