apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  
  labels:
    app: {{ .Values.app.name }}
data:
  POSTGRES_URL: {{ .Values.postgres.url | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  LNCR_BASE_URL: {{ .Values.app.baseUrl | quote }}
  MERCADOPAGO_OAUTH_URL: {{ .Values.app.mercadopago.oauthUrl | quote }}
  MERCADOPAGO_ORDERS_URL: {{ .Values.app.mercadopago.ordersUrl | quote }}
