apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      initContainers:
        - name: db-check
          image: postgres:15.7-alpine
          command:
            - sh
            - -c
            - |
              echo "Waiting for PostgreSQL to be ready..."
              until pg_isready -h {{ .Values.postgres.containerName }} -p 5432 -U postgres; do
                echo "PostgreSQL is not ready yet. Waiting 5 seconds..."
                sleep 5
              done
              echo "PostgreSQL is ready!"
      containers:
        - name: {{ .Values.app.containerName}}
          image: "{{ .Values.app.image.repository }}{{- if .Values.app.image.tag }}:{{ .Values.app.image.tag }}{{- end }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.port }}
          env:
            - name: LNCR_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.name }}-config
                  key: LNCR_BASE_URL
            - name: MERCADOPAGO_ORDERS_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.name }}-config
                  key: MERCADOPAGO_ORDERS_URL
            - name: MERCADOPAGO_OAUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.name }}-config
                  key: MERCADOPAGO_OAUTH_URL
            - name: POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.name }}-config
                  key: POSTGRES_URL
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-secret
                  key: POSTGRES_PASSWORD
            - name: MERCADOPAGO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-secret
                  key: MERCADOPAGO_CLIENT_ID
            - name: MERCADOPAGO_SECRET_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-secret
                  key: MERCADOPAGO_SECRET_ID
            - name: MERCADOPAGO_POS_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-secret
                  key: MERCADOPAGO_POS_ID
          volumeMounts:
            - name: images-storage
              mountPath: /app/images
          resources:
            requests:
              memory: {{ .Values.resources.lanchesCaieirasApp.requests.memory }}
              cpu: {{ .Values.resources.lanchesCaieirasApp.requests.cpu }}
            limits:
              memory: {{ .Values.resources.lanchesCaieirasApp.limits.memory }}
              cpu: {{ .Values.resources.lanchesCaieirasApp.limits.cpu }}
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: images-storage
          hostPath:
            path: {{ .Values.storage.images.hostPath | replace "C:/" "/run/desktop/mnt/host/c/" | replace "\\" "/" | quote }}
            type: DirectoryOrCreate
