apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
  
  labels:
    app: {{ .Values.app.name }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: "{{ .Values.secrets.postgresPassword }}"
  POSTGRES_USER: "{{ .Values.secrets.postgresUser }}"
  MERCADOPAGO_CLIENT_ID: "{{ .Values.secrets.mercadopagoClientId }}"
  MERCADOPAGO_SECRET_ID: "{{ .Values.secrets.mercadopagoSecretId }}"
  MERCADOPAGO_POS_ID: "{{ .Values.secrets.mercadopagoPosId }}"

