name: Complete Infrastructure

env:
  TERRAFORM_VERSION: 1.5.7

on:
  workflow_run:
    workflows: ["Deploy Application"]  # Nome do workflow do repo app
    types: [completed]

jobs:
  complete-infra:
    name: Complete Infrastructure Setup
    runs-on: codebuild-github-lncr-iac-${{ github.run_id }}-${{ github.run_attempt }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Configure kubectl
      run: |
        aws eks update-kubeconfig --region us-east-1 --name lncr-prd-eks
    
    # - name: Get NLB DNS from EKS
    #   run: |
    #     # Buscar DNS do NLB criado pelo Helm
    #     NLB_DNS=$(kubectl get svc -n default -o jsonpath='{.items[?(@.spec.type=="LoadBalancer")].status.loadBalancer.ingress[0].hostname}' | head -1)
    #     if [ -z "$NLB_DNS" ]; then
    #       echo "Error: NLB DNS not found"
    #       exit 1
    #     fi
    #     echo "NLB_DNS=$NLB_DNS" >> $GITHUB_ENV
    #     echo "Found NLB DNS: $NLB_DNS"

    - name: Deploy API Gateway Configuration with NLB
      # env:
      #   TF_VAR_eks_dns_nlb: ${{ env.NLB_DNS }}
      run: |
        terraform init
        terraform apply \
          -target=module.api-gateway-integration \
          -var-file="prd.tfvars" \
          -auto-approve